CREATE TABLE tb_tarefas (
    id INT IDENTITY(1,1) PRIMARY KEY,
    titulo NVARCHAR(100) NOT NULL,
    descricao NVARCHAR(500),
    data_criacao DATETIME2 DEFAULT SYSDATETIME(),
    status NVARCHAR(20) DEFAULT 'PENDENTE'
);
